export const TW = 40;
export const TH = 20;
export const ENTITY_H = 22;
export const SHADOW_SCALE = 0.35;
export const ISO_SCALE = TW / 80;

export const WORLD_TILES = 28;
export const TILE_SIZE = 80;
export const AUTO_CONSTRUCT_SPACING = TILE_SIZE;
export const AUTO_CONSTRUCT_MODES = ['path', 'nearest'] as const;

export const LEASH_WARN = 0.88;
export const LEASH_DMG = 0;
export const MONSTER_SCALE = 1.22;

export {
  ACTIVE_BALANCE_CONFIG,
  BASE_MONSTERS,
  CARD_RARITY_WEIGHTS,
  DASH_COOLDOWN,
  DASH_DURATION,
  DASH_SPEED,
  EARLY_START_BONUS,
  FREE_DEPLOY_GOLD,
  LEVELUP_OFFER_COUNT,
  MAX_WEAPON_SLOTS,
  MONSTER_ATTACK_COOLDOWN,
  MONSTER_SPAWN_ATTACK_COOLDOWN_MAX,
  MONSTER_CONTACT_BUFFER,
  MONSTER_DEF,
  OUTPOST_ATK_DMG,
  OUTPOST_ATK_RANGE,
  OUTPOST_ATK_SPEED,
  OUTPOST_COST,
  OUTPOST_COST_RULES,
  OUTPOST_HP_BASE,
  OUTPOST_LEVEL_DAMAGE_MULTIPLIER,
  OUTPOST_LEVEL_RANGE_ADD,
  OUTPOST_MAX_LEVEL,
  OUTPOST_PLACEMENT,
  OUTPOST_RANGE,
  PLAYER_DASH_INVULN_BONUS,
  PLAYER_HIT_FLASH,
  PLAYER_HIT_INVULN,
  PLAYER_HP_BASE,
  PLAYER_RADIUS,
  PLAYER_SPEED,
  PLAYER_SPAWN_OFFSET_Y,
  REROLL_BASE_COST,
  SHOP_OFFER_COUNT,
  SHOP_REFRESH_COST,
  STARTING_DASH_CHARGES,
  STARTING_GOLD,
  STAT_UPGRADES,
  STRUCTURE_CONTACT_RADIUS,
  TOWER_ATK_DMG,
  TOWER_ATK_RANGE,
  TOWER_ATK_SPEED,
  TOWER_AURA_DMG,
  TOWER_AURA_R,
  TOWER_HP_BASE,
  TOWER_MULTISHOT,
  TOWER_RANGE,
  TOWER_UPGRADES,
  WAVE_CONFIG,
  WAVE_CRYSTAL_REWARD,
  WAVE_ENEMY_MIX,
  WAVE_INTERVAL,
  WAVE_SPAWN_CONFIG,
  WAVE_STARTING_DELAY,
  WEAPONS,
  META_UPGRADES,
  applyRuntimeBalance,
  buildInitialGameState,
  buildRuntimeBalance,
  computeCardGoldCost,
  computeEarlyStartBonus,
  computeOutpostCost,
  computeRerollBaseCost,
  getOutpostStatsForLevel,
  getWeaponMaxLevel,
  getWeaponStats,
  metaValueFromConfig,
} from './runtime-balance.ts';
